### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by talhadar90** [seungwoodev/metaverse#3]
Hi

I've installed the packages but when I visit localhost, it is just stuck on loading

![image](https://user-images.githubusercontent.com/47798478/153707042-adfa7fae-1557-445d-aa23-d746f8196880.png)

**Comment by seungwoodev** [comment]
@talhadar90
Hi :)

This is because the world.glb file is not included.
I shared it on Google Drive due to the file size problem, so you can download it, unzip it, put it in build/assets/ and run it.
https://drive.google.com/file/d/1jgLTQ_b19a60fwEN7FVKgKHOcG1hFxUK/view?usp=sharing
(I'm not sure if this file is the last version)

**Comment by talhadar90** [comment]
It works. 

Thankyou!
